### ISSUE TITLE
CSV Auto Loader assuming wrong type

### ISSUE THREAD

**Issue by pdet** [cwida/duckdb#1014]
The CSV Loader infers the type from a sample of the data, so for example, if I have a column
t1.phone=[99999999,88888888,+55(85)99999]
and I get unlucky and the sample only looks to my first two entries, it will assume my data type as integer and will break when inserting my last entry
Issuing an error like:
Conversion Error: Could not convert string '+55(85)99999' to INTEGER. (delimiter=	, quote=", escape=, header=TRUE)

From a user perspective in an unknown dataset, I think this behavior is unexpected. 

I think an easy fix is to give a more clear error message and let the user set a different sample size? But then it loses the automatic appeal a bit.

**Comment by pdet** [comment]
I think it needs to clearly state what happened [The auto-detection failed]  why [Sample size not sufficiently big] and how to fix it [Increase sample size with command X].

Again, I'm personally not a big fan of this, since the nicest thing about this command is that it doesn't need any input from the user.

I know @Mytherin suggested to buffer like 100k rows, which would solve this problem for small CSVs, or to have a flag “load_as_strings”, that just loads everything as varchar then the user converts himself whatever he wants.

Not sure if @tdoehmen has a particular view on this ;-)

**Comment by tdoehmen** [comment]
Let's start thinking about the worst-case scenario: There is only one inconsistent value that is positioned at the very end of the last section that has not been sampled. So, virtually, the whole file would have to be scanned in order to detect this instance. 

For full automation, we thus actually need to scan the file twice (once for type detection, once for parsing). I could imagine that it makes sense to introduce an option to turn off sampling (which then makes the parser scan the whole file for type detection). In that case, we could also buffer the first 100k rows, so that in the parsing run, the first 100k rows won't have to be read from disk anymore.
 
Sampling can then be considered as an optimization that has the tradeoff that it might fail (and provide a helpful error message which tells the user to increase the sample size or set columns-types to VARCHAR).

**Comment by tdoehmen** [comment]
@Mytherin you can assign this to me.

**Comment by Mytherin** [comment]
> Let's start with thinking about the worst-case scenario: There is only one inconsistent value and it is positioned at the end of the last file-section which was not selected for sampling. So, virtually, the whole file would need to be scanned in order to detect this instance.
> 
> So, for an un-failable type detection, we would need to scan the file twice (once for type detection, once for parsing) or buffer the un-parsed data during type detection. I could imagine that it makes sense to introduce an option to turn off sampling for type detection (and instead scan the whole file). In that case, we could also buffer the first 100k or so rows, so that in the parsing run, the first xxx rows won't have to be read from disk again.
> 
> We could then consider the sampling as an optimization that has the tradeoff that it might fail (and provide a helpful error message which tells the user to increase the sample size or set columns-types to VARCHAR).
> 
> We'd only have to decide which option (sampling/full-scan) should be the default.

I think the sampling should still be the default, with maybe a switch to full-scan if the file is small (e.g. <10MB). I think the most important part is actually changing the error message so that it is more clear in the case of auto detection (e.g. `"Could not convert value "55(85)99999" on line 97884 belonging to column "phone number" to auto detected type INTEGER, consider either increasing the sample size (using SAMPLE_SIZE=X) or skipping column conversion (ALL_VARCHAR=1)"`.) That way the user can clearly see what went wrong and there are clear steps that are described that the user can follow to fix the problem.

**Comment by tdoehmen** [comment]
@Mytherin @hannesmuehleisen can be closed
