### ISSUE TITLE
Unsigned types are not supported

### ISSUE THREAD

**Issue by ananis25** [cwida/duckdb#1023]
Hi

Trying to read an Arrow table threw a slightly cryptic error - "Not implemented: Unsupported Arrow type C", which turned out to be due to a column of the type `uint8`.
I was just curious if this is to ensure compatibility with the SQL standard (I recall postgres didn't have unsigned types either)? Would it be useful to highlight this in the documentation?

**Comment by hannesmuehleisen** [comment]
Yes those should be supported, in the very least by using the next bigger signed type.

**Comment by Mytherin** [comment]
This topic does raise the question: should we support unsigned types in the engine? One of our goals is interoperability with other data formats, and many other libraries we care about interacting with support unsigned types: [NumPy/Pandas](https://numpy.org/doc/stable/user/basics.types.html), [Parquet](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md), [Arrow](https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv4N5arrow4Type4typeE) and [MySQL](https://dev.mysql.com/doc/refman/5.7/en/integer-types.html). Of course converting is always an option, but less than ideal (preferably we wouldn't convert uint64_t to hugeint, for example).

Unsigned types and operations can also be useful in some cases; for example, functions that can only take a non-negative number can take an unsigned integer as parameter. Any auto-cast from a signed type will then enforce that the number is non-negative. We actually already kind of have an unsigned types: `HASH` and `POINTER`.

The main downside to adding unsigned types would be increased binary size from supporting the extra types. Actually adding the unsigned types is not very difficult (mainly adding some more type switches, casts and numeric function overloads). It's rather similar to the hugeint support, except easier because the unsigned types are built-in.

**Comment by hannesmuehleisen** [comment]
Indeed it raises this question, this is why i said "in the very least". I do think we should just add those types, as you said they are in loads of systems we interoperate with.

**Comment by hannesmuehleisen** [comment]
This was implemented, thanks, @pdet
