### ISSUE TITLE
Duckdb can't be built when located within a sub_subdirectory

### ISSUE THREAD

**Issue by tkschmidt** [cwida/duckdb#1116]
Hey,
thx for the nice project. I added it as a git submodule, included it via 
`add_subdirectory(${PROJECT_SOURCE_DIR}/third_party/duckdb)` but couldn't built `duckdb`. 

**Problem**:
The include of `extension_helper.hpp` in https://github.com/cwida/duckdb/blob/master/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp couldn't find it.

**Quick solution:**
Not sure if worth a PR or you just want to add it as a minimal change in you next commit to master/dev.
https://github.com/tkschmidt/duckdb/commit/ccae3aea48afdc26e245f063551775031340fbb7

I also checked a fresh built from this branch and seems to be fine now for both situations:
- duckdb as CMAKE_PROJECT_DIR
- duckdb as subdirectory

Do you want also an example project that shows the issue?

Best and thx for everything,
Tobi

**Comment by Mytherin** [comment]
The problem seems to be that we use `${CMAKE_SOURCE_DIR}` to set include paths for extensions. Rather than changing the include path to a relative one I think a better solution would be to change this to `${PROJECT_SOURCE_DIR}`. I have opened a PR (#1117) that makes this change. Could you verify if that also solves the problem for you?

**Comment by tkschmidt** [comment]
works like a charm 👍

**Comment by Mytherin** [comment]
Thanks! In that case I will merge the PR and consider this issue resolved.
