### ISSUE TITLE
parquet file querying works in 0.2.2 but not in 0.2.3

### ISSUE THREAD

**Issue by akkishore** [cwida/duckdb#1201]
The following is the schema of parquet file:

```
required group field_id=0 sales_schema {
  required binary field_id=1 region (UTF8);
  required binary field_id=2 country (UTF8);
  required binary field_id=3 item_type (UTF8);
  required binary field_id=4 sales_channel (UTF8);
  required binary field_id=5 order_priority (UTF8);
  required binary field_id=6 order_date (UTF8);
  required binary field_id=7 order_id (UTF8);
  required binary field_id=8 ship_date (UTF8);
  required int64 field_id=9 units_sold;
  required float field_id=10 unit_price;
  required float field_id=11 unit_cost;
  required double field_id=12 total_revenue;
  required double field_id=13 total_cost;
  required double field_id=14 total_profit;
}
```

**Loading it in as a view and running a select query** works fine in python duckdb 0.2.2 but in python duckdb 0.2.3 throws `RuntimeError: unsupported type: BLOB`

I have used sample CSV files from http://eforexcel.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/ and converted to Parquet using https://gist.github.com/samvel1024/16aaa32f251ef95b6187082cdd6491f7

**Comment by Mytherin** [comment]
If possible could you send the Parquet files you generated to my email (raasveld@cwi.nl)?

**Comment by Mytherin** [comment]
I had a look at this and this is not related to the Parquet reader. The problem is that you are using a legacy Parquet writer that does not correctly set the UTF8 flag for strings in the file. As a result all the string columns are written as blobs instead. The error occurred when loading these blobs into Python as the Python API did not have support for reading blobs yet. I have added blob support to the Python API in #1202.

In Spark they have a setting `spark.sql.parquet.binaryAsString` to deal with these legacy Parquet files:

    Some other Parquet-producing systems, in particular Impala, Hive, and older versions
    of Spark SQL, do not differentiate between binary data and strings when writing out the
    Parquet schema. This flag tells Spark SQL to interpret binary data as a string to provide
    compatibility with these systems.

We should add this flag as well.

As a work-around for now you can manually decode the blob columns before loading them into Python, e.g.:

```sql
SELECT decode(region), decode(country), ... FROM parquet_scan('sales.parquet');
```

**Comment by akkishore** [comment]
Thanks for the quick resolution, closing the issue.
