### ISSUE TITLE
sqllogictest ignores column types

### ISSUE THREAD

**Issue by evanj** [cwida/duckdb#1212]
The sqllogictest format includes column types (I, T, R), but they are ignored when comparing results. This means a number of the DuckDB tests have the incorrect column types in them.

A simple example, where the first column should be T instead of I: https://github.com/cwida/duckdb/blob/master/test/sql/types/blob/test_blob_operator.test#L34

A complex example: The sqllogictest format does not support arrays, but the array_agg test does implicit string comparisons: https://github.com/cwida/duckdb/blob/master/test/sql/types/list/array_agg.test#L9

From my brief look at the upstream version, and the version in DuckDB, neither of them actually check column types. Changing this would be a substantial diversion from the upstream version. Is this a change you would be interested in?

Advantages:
* Tests would verify that the types are correct. If DuckDB were to return strings for every result column, it would continue to pass the sqllogictest suite. This would allow tests to distinguish between the values of `"1"` and `1`.

Disadvantages:
* Substantial change from the upstream version.
* SQLite (and maybe DuckDB?) is very loose about types in general, so possibly this "string comparison" actually matches what the engine does?
* Probably will either need explicit casts to string, or need to introduce additional column types (at least arrays, possibly others?)

**Comment by Mytherin** [comment]
This is something that I considered when I initially converted our old test suite to the sqllogictests, which is why many of the older tests do have the correct markers, but I ended up having to ignore the column type markers. Nowadays I just use "I" everywhere and use it only as indication of how many columns are in the result.

As you mentioned, the original sqllogictests also ignore type markers besides using the column count, and hence actually treating incorrect type markers as errors breaks compatibility. Since we also run SQLite's test suite this is highly undesirable, there are thousands of tests there that would break if we introduce this change. 

The type markers as they are originally included are also very limited, since they only include three types (I, T and R). DuckDB has many more types: i8/i16/i32/i64/i128, float, double, varchar, date, time, timestamp, blob, interval, lists, structs, decimals, ... The basic type markers as they are included in the SQLite tests are not very useful because they are simply not detailed enough, but extending the type markers with other types will make the system too complicated and diverge even more from the original, which is also not desirable.

In the end, for tests where it matters (e.g. the [read_csv_auto tests](https://github.com/cwida/duckdb/blob/ae64c7e9368f8bdfad2d2e37d3601a96f988baae/test/sql/copy/csv/auto/test_type_detection.test)) we simply use the `typeof` function to test the types as they are output. I think that is sufficient. Changing this is an immense effort that will break compatibility with the original format for not much gain in my opinion.
