### ISSUE TITLE
Comparison with boolean unexpectedly evaluates to false

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#1224]
Consider the following test case:

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0(c0) VALUES (-1);
INSERT INTO t0(c0) VALUES (0);
SELECT * FROM t0 WHERE t0.c0::BOOL = true; -- expected: {-1}, actual: {}
```
Unexpectedly, no row is fetched. I think this is a regression bug. SQLancer found it using the TLP WHERE oracle, because the following two queries unexpectedly did not compute the same result set:

```sql
SELECT * FROM t0;
SELECT * FROM t0 WHERE t0.c0::BOOL = true UNION ALL SELECT * FROM t0 WHERE (NOT ((((t0.c0) ::BOOLEAN))=true)) UNION ALL SELECT * FROM t0 WHERE ((t0.c0::BOOL = true) IS NULL);
```
I found this using DuckDB version d27dd50d3 while attempting to upgrade the DuckDB version used in SQLancer's CI tests (see https://github.com/sqlancer/sqlancer/pull/257).

**Comment by Mytherin** [comment]
Thanks for the report, and excellent find again! This was indeed a regression that was introduced by the new statistics propagation optimizer. The statistics propagator takes the min/max statistics of the base table and propagates them through the plan.

In this case, the base table had the statistics `[min: -1, max: 0]`. It would then resolve the expressions in the `WHERE` clause and update the statistics. However, it assumed the casting would preserve order, i.e. `new min = CAST(old_min), new_max = CAST(old_max)`.

For numeric casts this is true (e.g. if we cast from INT -> DOUBLE), but for booleans this is not true, because `-1::BOOL = true`, and `0::BOOL = false`. The `min/max` would therefore be turned into `min: true, max: false`.

These statistics lead the system to believe the comparison with true would always return false: since the max of the column is false, it obviously can't contain true. This lead the optimizer to incorrectly strip away the entire plan as can be seen in the explain:

```sql
D CREATE TABLE t0(c0 INT);
D INSERT INTO t0(c0) VALUES (-1);
D INSERT INTO t0(c0) VALUES (0);
D SELECT * FROM t0 WHERE t0.c0::BOOL = true;
D explain SELECT * FROM t0 WHERE t0.c0::BOOL = true;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│        EMPTY_RESULT       │
└───────────────────────────┘                             
```

I have fixed it now in #1225 by disabling statistics propagation for boolean casts, which fixes the problem. Thanks :)
