### ISSUE TITLE
Data conversion: Virtual table streaming and exporting with EXPORT DATABASE

### ISSUE THREAD

**Issue by dforsber** [cwida/duckdb#1311]
DuckDB is powerful as it can also write Parquet as well as read it among other formats. This naturally brings up a question that can DuckDB be used to stream data from source to destination while doing "local" transformations that do not require full table presence (like perhaps sorting without an index). 

In our tests we have noticed (@jupiter) that DuckDB uses quite a lot memory (compared to e.g. nodejs streaming solution) when reading e.g. from CSV file (`read_csv_auto `) and exporting it to Parquet without any transformations or sorting. Does this mean that source data size contributes/scales with DuckDB memory consumption? What if the CSV file would be "infinite", never ending file?

**Comment by Mytherin** [comment]
DuckDB has a streaming engine and is capable of streaming data from one source to another without materialising anything in memory. However, that is of course only possible if nothing is explicitly materialized. If you run a `CREATE TABLE` statement (or similar), the result will be materialized (either in-memory or on disk).

In the title you mention you use `EXPORT DATABASE` to export to a Parquet file. Are you first loading the CSV file into a table and then exporting that table? Because in that case the rising memory usage is expected - you are loading the data into DuckDB first in its entirety. If you want to stream data from one source to another, you will need to create a pipeline from source A to sink B. For example, to go from CSV to Parquet you could use the following SQL statement:

```sql
D COPY (SELECT * FROM read_csv_auto('test.csv')) TO 'result.parquet' (FORMAT PARQUET);
D SELECT * FROM read_parquet('result.parquet');
┌─────────┬─────────────────────┬─────────────────────┬─────────┐
│ column0 │       column1       │       column2       │ column3 │
├─────────┼─────────────────────┼─────────────────────┼─────────┤
│ 1       │ 2019-08-18 18:33:59 │ 2019-08-18 23:10:24 │ 0       │
│ 2       │ 2019-08-18 13:37:56 │ 2019-08-18 16:40:31 │ 0       │
│ 3       │ 2019-08-18 14:58:42 │ 2019-08-19 00:30:24 │ 0       │
│ 4       │ 2019-08-18 08:45:16 │ 2019-08-18 13:37:46 │ 0       │
│ 5       │ 2019-08-18 14:50:06 │ 2019-08-18 19:24:53 │ 0       │
│ 6       │ 2019-08-18 16:41:01 │ 2019-08-18 21:37:11 │ 0       │
│ 7       │ 2019-08-18 19:25:03 │ 2019-08-19 04:56:45 │ 0       │
│ 8       │ 2019-08-18 07:01:33 │ 2019-08-18 14:58:24 │ 0       │
│ 9       │ 2019-08-18 13:06:30 │ 2019-08-18 14:50:03 │ 0       │
│ 10      │ 2019-08-18 16:21:38 │ 2019-08-18 18:05:26 │ 0       │
│ 11      │ 2019-08-18 18:05:29 │ 2019-08-19 03:36:10 │ 0       │
│ 12      │ 2019-08-18 10:02:59 │ 2019-08-18 11:46:47 │ 0       │
│ 13      │ 2019-08-18 10:04:23 │ 2019-08-18 13:06:26 │ 0       │
│ 14      │ 2019-08-18 16:40:36 │ NULL                │ 0       │
│ 15      │ 2019-08-18 18:33:32 │ NULL                │ 0       │
│ 16      │ 2019-08-18 07:01:34 │ 2019-08-18 08:45:40 │ 0       │
│ 17      │ 2019-08-18 08:45:44 │ 2019-08-18 18:32:51 │ 0       │
│ 18      │ 2019-08-18 07:01:33 │ 2019-08-18 10:02:54 │ 0       │
│ 19      │ 2019-08-18 07:01:34 │ 2019-08-18 08:45:13 │ 0       │
└─────────┴─────────────────────┴─────────────────────┴─────────┘
```

If you are already doing this then the rising memory usage is not expected (and possibly a bug or missing feature).

**Comment by jtommaney** [comment]
That is extremely interesting, but leads to some questions.
 1) I am assuming the above would be single-threaded, is that correct? Are there portions of the workload run in parallel?
 2) Could the "SELECT * FROM read_csv_auto('test.csv'" include extended sql syntax (join, filter, aggregate, expressions, order)?

**Comment by Mytherin** [comment]
> I am assuming the above would be single-threaded, is that correct? Are there portions of the workload run in parallel?

Currently it would be single-threaded, but in principle nothing stops it from being done in parallel. A regular pipeline (source -> sink) is created that can be parallelized if both the source and sink support it. Currently the CSV writer and Parquet writer do not support parallelism.

Adding parallelism would be relatively simple, but currently not yet implemented because it messes up the write order (e.g. if you would write a table to a CSV file in parallel, the table would not be in its original insertion order). We will likely add an option to enable this in the future, but opt-in because it has a "semi-destructive" effect of changing the order in which tuples are written.

> Could the "SELECT * FROM read_csv_auto('test.csv'" include extended sql syntax (join, filter, aggregate, expressions, order)?

Any SELECT query is supported there. You can also use views (e.g. `SELECT * FROM view`) which could contain any arbitrary query again.

**Comment by jupiter** [comment]
Excellent. We missed that it is possible with `COPY` but have found that all the info we needed is [here](https://duckdb.org/docs/sql/statements/copy). We can probably close this issue.
