### ISSUE TITLE
Does DuckDB work with single writer, multiple readers?

### ISSUE THREAD

**Issue by fintron** [cwida/duckdb#1330]
I have a use-case where I have one process continually writing to a DB and multiple readers who are reading from the DB.

Does DuckDB support for this use-case? Docs say multireader is ok, but not sure if that also allows for one writer.

**Comment by hannesmuehleisen** [comment]
These are separate processes, right? This works fine if you are talking about threads in a single process, but if multiple processes access a single DuckDB database file at the same time, they all need to be in read-only mode.

**Comment by tlbtlbtlb** [comment]
May I suggest making this more prominent in the documentation?

Nothing on the home page suggests that you can't have multiple processes except in read-only mode. It ought to be in the "When not to use" column.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/219508/108526705-4e504680-7286-11eb-864a-27ea03c0bc75.png">

**Comment by hannesmuehleisen** [comment]
@tlbtlbtlb I have added "Writing to a single database from multiple concurrent processes" to the "When not to use DuckDB" section. Thanks for the suggestion. Whats the use case you were thinking about there? This restriction is mostly due to the lack of a database server that would be otherwise holding and synchronising transaction states. You can write to a duckdb file from concurrent threads within one and the same process though, is that not an option for you?

**Comment by tlbtlbtlb** [comment]
It's possible I can make it work. The single-process restriction just caught me by surprise because I'd built a previous version with sqlite3 and separate binary blob files. I was hoping to rewrite with all the data in DuckDB, because managing the blob files is error-prone.

My usage is mostly read-only queries, but I also store small bits of state in the database, like the last-used visualization settings for that data. I may be able to separate out the mutable state, and keep that in sqlite3. But I am a bit reluctant to have 2 similar-but-different database APIs in the same program.

I will think more about the best way to organize the data.
