### ISSUE TITLE
Binder error

### ISSUE THREAD

**Issue by TheGiamig** [cwida/duckdb#1386]
Hi, I'm replacing SQLite with DuckDB and I got a binder error from a previously working query .

The (simplified) table is `CREATE TABLE attribute(id BIGINT, object_id INTEGER, type INTEGER, value BLOB, time BIGINT);`

The query is `SELECT type, value, MAX(time) FROM attribute WHERE object_id = #MY_ID# AND time <= #MY_TIME# GROUP BY type;`

The error is: Binder Error: column must appear in the GROUP BY clause or be used in an aggregate function.

My intent is to retrieve, for a given object_id and time, the last value of each different type.

If I change the query this way `GROUP BY type, value` the binder works but the result is not correct (many duplicates rows).

I cannot figure out the solution.
Thanks.

**Comment by Mytherin** [comment]
If the query originates from SQLite, semantically it is equivalent to using the `FIRST` aggregate over the `value` clause:

```sql
SELECT type, FIRST(value), MAX(time) FROM attribute WHERE object_id = #MY_ID# AND time <= #MY_TIME# GROUP BY type;
```

DuckDB is more strict on ungrouped columns in aggregates by default, like e.g. Postgres. This is because for ungrouped/unaggregated columns the semantics of *which* `value` to return is unclear. We offer the aggregate `FIRST` which essentially means "the first value we encounter that belongs to this group". This is more or less what SQLite would do in this situation, but might not be exactly what you are looking for.

If you want to fetch the value that corresponds to the max time for each group (i.e. the latest `value`), you could use a correlated subquery, such as:

```sql
SELECT type, value
FROM attribute
WHERE object_id = #MY_ID# AND time <= #MY_TIME#
  AND time = (SELECT MAX(time) FROM attribute a1 WHERE a1.type=attribute.type)
```

Alternatively, there is also the (very recently merged, only available on master) argMax function you can use:

```sql
SELECT type, argMax(value, time)
FROM attribute
```

**Comment by TheGiamig** [comment]
Mark thank you very much!
Sorry for my questions, DBs are not my favorite topic..

argMax function is an optimized path or performance aren't the point?

The solution with the subquery seems to me non correct for the job.
The table attribute contains a "timed series". The software receives many "attributes" updates for an "object" (e.g. temperatures for a building).
`value` is the raw data, `type` describes the attribute, but also depends from object (e.g. type 1 can be temperature for object 3 but lux for object 4).
So the query have to fetch the latest `value` for each `type` with `time` <= of a certain timestamp.
Why you think the query `SELECT type, FIRST(value), MAX(time) FROM attribute WHERE object_id = #MY_ID# AND time <= #MY_TIME# GROUP BY type;` is not correct? Perhaps FIRST(value) will be the first value encountered but not for sure the one with MAX(time)?

Cheers

**Comment by Mytherin** [comment]
> argMax function is an optimized path or performance aren't the point?

It should be faster than the subquery since it can be computed in a single scan over the table without doing a join; the point of it is indeed performance and readability. It should give the same result as the subquery.

> The solution with the subquery seems to me non correct for the job.
The table attribute contains a "timed series". The software receives many "attributes" updates for an "object" (e.g. temperatures for a building).
value is the raw data, type describes the attribute, but also depends from object (e.g. type 1 can be temperature for object 3 but lux for object 4).
So the query have to fetch the latest value for each type with time <= of a certain timestamp.

This is exactly what the subquery is doing, but it is doing it in two parts. First, it finds the maximum `time` for each of the different attribute types for the given object ID. This is the subquery:

```sql
SELECT MAX(time)
FROM attribute a1
WHERE a1.type=attribute.type AND object_id = #MY_ID# AND time <= #MY_TIME#
```

Then, for every observation, it finds the corresponding value by looking this back up in the main table using a (implicit) join:

```sql
SELECT type, value
FROM attribute
WHERE object_id = #MY_ID# AND time <= #MY_TIME#
  AND time = (...)
```


> Why you think the query SELECT type, FIRST(value), MAX(time) FROM attribute WHERE object_id = #MY_ID# AND time <= #MY_TIME# GROUP BY type; is not correct? Perhaps FIRST(value) will be the first value encountered but not for sure the one with MAX(time)?

Exactly; if there are multiple observations with `time <= #MY_TIME#`, the result is not defined. It returns the first value encountered, which is likely the observation with the lowest time (but again, this depends on what your data looks like in the physical system, it is not defined).

**Comment by TheGiamig** [comment]
Mark, needless to say you were right :)
Sometimes also a copy&paste can be difficult :D

Now the binder error is fixed and the query fetches correctly the data.. but.. performaces aren't so good.
Sure the subquery is heavy when the table gets bigger (I'm testing with 5million entries).

I would try master code for the argMax() function but a the moment I cannot compile it cause a problem with `pcg128_t`
I added the amalgamation version (duckdb.cpp/hpp) to my project without linking the dll.
Maybe it's my mistake but the amalgamation, also version 0.2.4, give errors cause some `#include` are still there.
Another error is the multiple declaration of `typedef uint64_t idx_t;`

If useful (and if isn't my mistake), I can give you much details.

**Comment by hannesmuehleisen** [comment]
I would say the binder error has been resolved. If you're unable to compile, open another issue please. Also have a look at the binaries from the master branch here: https://github.com/cwida/duckdb/releases/tag/master-builds
