### ISSUE TITLE
Python API should be able to execute multiple statements in one API call

### ISSUE THREAD

**Issue by pdet** [cwida/duckdb#400]
sqlite3.Warning: You can only execute one statement at a time.

e.g.,
```python
import duckdb
CREATE_SCHEMA = """
CREATE TABLE tbl_eins(
	a INTEGER 
);
CREATE TABLE tbl_zwei(
	a INTEGER 
);
 """

db = duckdb.connect('quack.db')
duck_cursor = db.cursor()
duck_cursor.execute(CREATE_SCHEMA)
```

**Comment by hannesmuehleisen** [comment]
Does the Python SQLite API support this? But we have support for this in the sqlite3_api_wrapper. I wonder whether we should rewrite the Python client to just use the stock Python sqlite3 module code as well (with some extensions like fetch_df)...

**Comment by Mytherin** [comment]
It seems that the Python SQLite API does not support this with the execute method, e.g. this fails:
```python
import sqlite3
con = sqlite3.connect(':memory:')
cursor = con.cursor()
cursor.execute("""
CREATE TABLE integers(i INTEGER);
CREATE TABLE strings(v VARCHAR);
""")
```

However, SQLite seems to have a `executescript` method (which we do not have) that does allow multiple statements:
```python
import sqlite3
con = sqlite3.connect(':memory:')
cursor = con.cursor()
cursor.executescript("""
CREATE TABLE integers(i INTEGER);
CREATE TABLE strings(v VARCHAR);
""")
```

I would argue we should support multiple statements in the `execute` method as long as there are no parameters passed along. The problem is that once there are parameters it gets a bit more tricky. Suppose you have the following statements:

```python
cursor.execute("""
INSERT INTO integers VALUES (?);
INSERT INTO strings VALUES (?);
""", (3, "hello"))
```

Now the first parameter goes into the first query, and the second parameter goes into the second query. While we can resolve that, it seems very messy and I think it would be better to just throw an exception in this case.

**Comment by Alex-Monahan** [comment]
Hey Folks!

We are running into cases where it would be helpful to have this feature. I also found the executemany function, but that does not seem to support this functionality either. Your plan to add this into execute in the case where no parameters are passed would work perfectly for us.

As a part of our testing, I'm throwing a ton of semicolons in other places (in comments and in strings) to make sure that our manual regex parsing works for splitting statements apart. Here it is in case it is helpful, although your SQL parser is likely to be immune!

--Multistatement testing; testing
/*  test;   
--test;
;test */
create table temp_test as 
select
	'testing_temp;' as temp_col
;
select * from temp_test;


Thanks,
Alex

**Comment by Mytherin** [comment]
This should be implemented now in the Python client.
