### ISSUE TITLE
Question: sqlite3_api_wrapper batch-insert performance

### ISSUE THREAD

**Issue by Schaefer-Thomas** [cwida/duckdb#494]
Hi guys, great project!

Maybe you could give me an advice on where to investigate further with the following minor annoyance:
I'm experiencing very low insert performance (2,5k rows/s, tried different batch_sizes) with sqlite3_api_wrapper and  xerial/sqlite-jdbc.
Do you think, it could be caused by the sqlite3_api_wrapper or should I look deeper into the sqlite-jdbc-project?

Thank you very much!

**Comment by Schaefer-Thomas** [comment]
Oh, just saw, that you have your own jdbc-driver on the way! I will try this one.

**Comment by Mytherin** [comment]
Thanks for the kind words :)

I assume you are using INSERT INTO statements to load the data, correct? Currently INSERT INTO statements are not very well optimized. They are quite slow because every statement passes through the entire engine. In the future we want to optimize this scenario more, but for now it has not been one of our priorities.

You can find some benchmarks on [different append strategies here](https://www.duckdb.org/benchmarks/append.html).

In the C++ API, we provide the Appender class that allows for much faster appends. In the sqlite api wrappers, we don't have a similar method. One work around for now could be to write the data to a CSV and then load the CSV into the database, but this is a bit dirty.
