### ISSUE TITLE
Query results in an error "INTERNAL: Failed to bind column reference "c0" [5.0] (bindings: [6.0])"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#506]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
SELECT * FROM t1 JOIN t0 ON t1.c0 < t1.c0 - t0.c0 WHERE t0.c0 <= t1.c0; -- Error: INTERNAL: Failed to bind column reference "c0" [5.0] (bindings: [6.0])
```
Unexpectedly, the `SELECT` results in an error `INTERNAL: Failed to bind column reference "c0" [5.0] (bindings: [6.0])`.

I found this based on the latest master commit (4ad62e9e13f4a1b3c6452bcb4f5f31eac3d86053).

**Comment by Mytherin** [comment]
Good catch, actually triggers an assertion in DEBUG mode as well!

**Comment by Mytherin** [comment]
Fixed this in 801101000f874aac259bb8f5af30983a03475fba.

The bug here was in the join order optimizer: the comparison `t1.c0 < t1.c0 - t0.c0` was split into two sides (`t1.c0` and `t1.c0 - t0.c0`). However, because both sides contain a column from `t1`, the comparison could not be split up into a LEFT and RIGHT side. This triggered an assertion in debug mode, and resulted in a binding failure in release mode (as likely binding `t1.c0` was attempted against table `t0`, which is obviously not possible).

**Comment by mrigger** [comment]
Thanks for these detailed explanations! They are very useful for me.

**Comment by Mytherin** [comment]
No problem :) It's also potentially useful documentation for later, in case we trigger a similar bug
