### ISSUE TITLE
LEFT JOIN on column with NULL value results in a segmentation fault

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#508]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t0(c0) VALUES (0);
INSERT INTO t1(c0) VALUES (NULL);
SELECT * FROM t1 LEFT JOIN t0 ON t0.c0=t1.c0; -- Segmentation fault
```
Unexpectedly, the `SELECT` results in a segmentation fault:
```
build/release$ ./duckdb_cli 
SQLite version DuckDB 340d867b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE t0(c0 INT);
sqlite> CREATE TABLE t1(c0 INT);
sqlite> INSERT INTO t0(c0) VALUES (0);
sqlite> INSERT INTO t1(c0) VALUES (NULL);
sqlite> SELECT * FROM t1 LEFT JOIN t0 ON t0.c0=t1.c0; -- Segmentation fault
Segmentation fault
```
I found this bug based on commit 340d867b232b56faf198594e40adba733ecb7bc8.

**Comment by Mytherin** [comment]
Fixed this in c40e4ca4b08c65213d74f6f4349d46cf5c25f430. The issue was that the `found_match` array that keeps track of whether or not a match for the tuple had been found was initialized *after* we filtered NULL values. Since in this example the probe side only contained NULL values, this array was never initialized, hence resulting in a segmentation fault when trying to access it.
