### ISSUE TITLE
SIMILAR TO results in an incorrect result

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#510]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0(c0) VALUES (-10);
SELECT * FROM t0 WHERE t0.c0 NOT SIMILAR TO 0; -- expected: {-10}, actual: {}
```
Unexpectedly, the row in `t0` is not fetched. As expected, the negated predicate does not fetch any rows:
```sql
SELECT * FROM t0 WHERE t0.c0 SIMILAR TO 0; -- {}
```

I'm a bit confused about this case, since DuckDB seems to indicate that the negated predicate should evaluate to TRUE:
```sql
SELECT t0.c0 SIMILAR TO 0 FROM t0; -- true
```

I found this bug based on the latest master commit (340d867b232b56faf198594e40adba733ecb7bc8).

**Comment by Mytherin** [comment]
Fixed this in 0ba277225e9748b805dd9bf0270da75ec8db286b. The issue was that `SIMILAR TO` incorrectly used partial match semantics. Because of that, `'-10' SIMILAR TO '0'` resulted in a match (because `'0'` is contained within `'-10'`). This should be fixed now and `SIMILAR TO` requires an entire string match just like `LIKE` does.
