### ISSUE TITLE
Query with an AND predicate, NOT and comparison yields an incorrect result

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#517]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t0(c0) VALUES (0);
INSERT INTO t1(c0) VALUES (0);
SELECT * FROM t1, t0 WHERE NOT ((t1.c0 AND t0.c0) < 0); -- expected: {0|0}, actual: {}
```
Unexpectedly, the query does not fetch a row. The predicate should evaluate to `TRUE` for the rows in t0, and t1. The negated predicate works as expected and does not fetch any rows:
```sql
SELECT * FROM t1, t0 WHERE ((t1.c0 AND t0.c0) < 0); -- {}
```
I found htis based on the latest commit to master (9795d18b6a6e250a4076fa448f248287e76f5693).

**Comment by Mytherin** [comment]
Fixed this in d88e21d926e732096081ee8afda03d70310bee2d. The issue was that in the planning of a join with an expression in the form of `NOT(comparison)` we tried to invert the underlying comparison, e.g. `NOT(x < 0)` is equivalent to `x >= 0`. The problem is that we did this, then tried to split the comparison into a left and right side, and if this did not succeed we did not properly revert the comparison.

In this query what it would mean is the following:
```sql
-- original expression
NOT((t1.c0 AND t0.c0) < 0)
-- transform into:
(t1.c0 AND t0.c0) >= 0
-- cannot divide into left/right side! treat as arbitrary expression
NOT((t1.c0 AND t0.c0) >= 0) -- <= BUG!
```

I now moved this inversion of the NOT to the parser, so the parser would already invert `NOT(x <y)` to `x>=y`. This also makes the code cleaner in general :)
