### ISSUE TITLE
Query with JOIN and WHERE condition unexpectedly fetches a value not present in the table

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#527]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t0 VALUES (0);
INSERT INTO t1 VALUES (1), (1);
SELECT t0.c0 FROM t0 JOIN t1 ON t0.c0=(t1.c0 IS NULL) WHERE t0.c0 NOT IN (t1.c0); -- expected: {0, 0}, actual: {1, 1}
```
Unexpectedly, the query fetches values for `t0.c0` that are not present in the table.

Removing the `WHERE` clause results in the correct values being fetched:
```sql
SELECT t0.c0 FROM t0 JOIN t1 ON t0.c0=(t1.c0 IS NULL); -- {0, 0}
```

This bug might be related to https://github.com/cwida/duckdb/issues/525. However, in contrast to the bug referenced in the issue, this bug doesn't cause an assertion error in the debug build, so I assume that they are different bugs.

I found this bug based on commit 3f0eb5134512c6097805998ccc5eb44476534736.

**Comment by Mytherin** [comment]
This bug was indeed related to #525, and the fix for that also fixed this bug :)

The reason the assertion was not triggered in this case was because, while the binding was incorrect, the column types did match as both the columns are of type INT. In #525 an assertion was triggered because an INT column was fetched instead of a FLOAT column, which resulted in a type mismatch.

**Comment by mrigger** [comment]
Thanks for the feedback! I'll consider this bug report as a duplicate one.
