### ISSUE TITLE
Incorrect result for query that uses REGEXP_MATCHES()

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#528]
Consider the following statements:

```sql
CREATE TABLE t0(c0 VARCHAR);
INSERT INTO t0(c0) VALUES (0.1);
SELECT * FROM t0 WHERE REGEXP_MATCHES(t0.c0, '1'); -- expected: {0.1}, actual: {}
```
Unexpectedly, the `SELECT` fetches no rows, even though the following query suggests that the predicate evaluates to `TRUE`:
```sql
SELECT REGEXP_MATCHES(t0.c0, '1') FROM t0; -- true
```
Prepending a `NOT` to the original query also results in no rows being fetched:
```sql
CREATE TABLE t0(c0 VARCHAR);
INSERT INTO t0(c0) VALUES (0.1);
SELECT * FROM t0 WHERE NOT REGEXP_MATCHES(t0.c0, '1'); -- {}
```
I'm not sure which of the behaviors is expected, but one of them should fetch a row. I found this based on commit 3f0eb5134512c6097805998ccc5eb44476534736.

**Comment by Mytherin** [comment]
Fixed in 1035a091f6feba4cc1c37bea5dda3d3ccfcacd17; this was a bug with an optimizer we had that added a range filter based on a regex. In this case, the range filter added was `t0.c0 >= '1' AND t0.c0 <= '1'`. However, as `regexp_matches` performs a partial match, this range filter is incorrect. It can only be applied for full regex matches.
