### ISSUE TITLE
SELECT on DATE column with a large negative value results in a "double free or corruption"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#531]
Consider the following statements:

```sql
CREATE TABLE t0(c0 DATE);
INSERT INTO t0 VALUES (-10000000);
SELECT c0 FROM t0; -- double free or corruption (out)
```
Unexpectedly, the `SELECT` results in a crash:

```
duckdb/build/release$ ./duckdb_cli 
SQLite version DuckDB 3f0eb513
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE t0(c0 DATE);
sqlite> INSERT INTO t0 VALUES (-10000000);
sqlite> SELECT c0 FROM t0; -- double free or corruption (out)
double free or corruption (out)
Aborted
```
I found this bug based on commit 3f0eb5134512c6097805998ccc5eb44476534736.

**Comment by Mytherin** [comment]
Good catch! Fixed in 409b26b96fd9daeb9117ec620f9046f6f657b8eb. The problem was that the CAST was not performed because DATE and INT32 share the same internal type, thus the system thought a CAST was not necessary. Now the correct SQL type is checked before not performing a cast, fixing this problem and throwing a proper exception.
