### ISSUE TITLE
Nested MAX() results in nondeterministic result or double free

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#540]
Consider the following statements:
```sql
CREATE TABLE t0(c0 VARCHAR);
INSERT INTO t0 VALUES ('aaaaaaaaaaaa');
SELECT MAX(agg0) FROM (SELECT MAX(t0.c0) AS agg0 FROM t0) as s0; -- nondeterministic result or crash
```
The `SELECT` results in an non-deterministic result when running it via JDBC, and in the following error when using the DuckDB CLI (maybe due to a different malloc() implementation?):
```
duckdb/build/release$ ./duckdb_cli 
SQLite version DuckDB 4ab3d451
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE t0(c0 VARCHAR);
sqlite> INSERT INTO t0 VALUES ('aaaaaaaaaaaa');
sqlite> SELECT MAX(agg0) FROM (SELECT MAX(t0.c0) AS agg0 FROM t0) as s0;
free(): double free detected in tcache 2
Aborted
```
I found this based on the latest master commit (4ab3d451a38fbc622d942fde9e52a15a849dfb27).

**Comment by Mytherin** [comment]
Good find again! Fixed in 7945aa5c9e591b715cf16d8ef0dc4c9612f08219. This was a problem I introduced in #536 when fixing min/max on strings; I incorrectly did not copy the aggregate into the result vector which lead to the same value being present in two hash tables. That then lead to the double free when the hash tables were cleaned up.
