### ISSUE TITLE
Assertions in the JDBC build of DuckDB?

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#545]
Is there an easy way to enable DuckDB assertions in the JDBC build? Would failing assertions be interesting?

**Comment by hannesmuehleisen** [comment]
Yes, that would indeed be interesting. Will look into creating such a build.

**Comment by Mytherin** [comment]
Two more things that might be interesting for testing:
* Setting vector size to 2, low vector size can trigger certain bugs on very small data sets that would otherwise require larger data sets
* Enabling query verification, this enables running both the optimized and unoptimized version of queries and will result in an exception being thrown if the results are different. This might slow down the testing process somewhat though, and also some care must be taken because in certain queries the unoptimized/optimized result being different is not a bug (i.e. if there is no ORDER BY clause and the order is different).

**Comment by hannesmuehleisen** [comment]
As a first step, I added a way to create a debug build of the JDBC driver: `make jdbcdebug` in the `jdbccompliance` branch.

**Comment by mrigger** [comment]
Great, thanks! I found the first failing assertion using it (https://github.com/cwida/duckdb/issues/547).

**Comment by hannesmuehleisen** [comment]
> Great, thanks! I found the first failing assertion using it (#547).
Excellent!
