### ISSUE TITLE
Data driven test suites

### ISSUE THREAD

**Issue by hawkfish** [cwida/duckdb#576]
It is most time-consuming to have to recompile test files in C++.  We should have a test suite that can just enumerate query scripts and execute them.

**Comment by Mytherin** [comment]
I'm not entirely opposed to this but I quite like the current test suite for debugging purposes. It is very easy to step into individual queries, and it is very flexible as you can run arbitrary code rather than just queries. For example, we have tests that involve restarting the database system, running parallel client connections, etc.

We could have a mix where we run simple tests from files and more complex ones stay as they are. We already kind of have that with the sqllogictests. The main benefit of that that I can see is that it would reduce initial compilation time.

I think that is a reasonable goal, especially for e.g. speeding up our CI pipelines, but for development I think the current setup is better. The tests take a while to compile on the first go, but unless you are changing the main API (e.g. connection.hpp or so) you should be recompiling only a single test which takes almost no time. If a test breaks you can run the exact test you want and step into the exact query where it breaks.

In a data driven testing model this is much more tricky. At least that is my experience from working with the sqllogictest suite. You have tests that run a bunch of different files, and the files themselves have a bunch of different queries. When an individual query in there breaks it is extremely annoying to extract and test. Perhaps we can improve on that, however, and make a data driven test suite that allows stepping into individual queries easily.

**Comment by hawkfish** [comment]
I'm not arguing for exclusively for a data-driven model, but in my experience as the test suite size increases, the _link_ time starts to go up.  With data-driven tests, there is little down side to making each test small (e.g. a single query), which in turn makes stepping in relatively simple when you run that single test.

Let's just keep in in mind because I have worked on two systems that had a subset of data-driven tests, one of which was Hyper(!)

**Comment by Mytherin** [comment]
The link time is indeed a good point. I think it is indeed a good idea to convert our simple tests to data driven tests, but we do need to be careful to allow for the running of individual tests and easily allow for setting breakpoints on individual queries. At least as they are now I think the sqllogictests are not sufficient, but perhaps we can adapt those instead of creating our own format.

**Comment by hannesmuehleisen** [comment]
Could we not also compile test directories, say, into several dynamically loaded libraries and the test runner just `dlopens()` them?

**Comment by Mytherin** [comment]
While that might alleviate the linking time a bit the data driven solution seems better to me. It would allow us to write tests without having any cruft, and changing anything in the client context/connection would not require a full test suite recompile, plus it would shave some time off of the CI builds.

I think if we do this properly we can make it nice to debug as well (i.e. we need a way to easily run a specific file AND break at a specific line in that file). Perhaps we can adjust the sqllogictest runner and change some tests to that format to see how it feels, and if it turns out to be worse we stay with our current solution.

**Comment by Mytherin** [comment]
I have now started working on this. We have chosen to adopt the sqllogictests, and modify the test runner to suit our needs. I am now in the process of converting all of our simple tests. Complex tests (e.g. involving running multiple connections or parallel usage of the APIs) will stay as compiled tests for now.

**Comment by Mytherin** [comment]
This is now implemented, [see here for a description](https://duckdb.org/docs/dev/testing.html).
