### ISSUE TITLE
DISTINCT malfunctions for BOOLEAN

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#581]
Consider the following statements:
```sql
CREATE TABLE t0(c0 BOOLEAN);
INSERT INTO t0 VALUES (NULL), (false);
SELECT DISTINCT t0.c0 FROM t0; -- expected: {NULL, false}, actual: {NULL, NULL}
```
Unexpectedly, the `DISTINCT` results in two `NULL` values being fetched. I found this bug based on the latest master version (ed92e9c555299378c86d4342c94663e65ab8eef7).

**Comment by Mytherin** [comment]
Nice find as always! The problem was that we store NULL values in hash tables using the smallest possible value in the domain. For booleans, however, we are supposed to use the smallest value in the int8_t domain. By accident we used the smallest value in the boolean domain for the FIRST aggregate, which is used in the DISTINCT. This caused the false to be transformed into a NULL.
