### ISSUE TITLE
Query with complex ORDER BY causes an incorrect rowid value

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#588]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES (1), (0), (1);
SELECT t0.rowid FROM t0 WHERE t0.rowid ORDER BY CASE ((t0.c0) ::BOOL) WHEN 1 THEN t0.rowid END; -- expected: {0, 2}, actual: {140671047175328, 2}
```
Unexpectedly, the `rowid` for the first row is some non-deterministic, large value. I found this based on commit dc352a3729f57252a1f6bfa18077fed9c4598a54.

**Comment by Mytherin** [comment]
Good find :) The rowid column is a generated column, that is internally compressed as a `sequence` vector. The CASE statement resulted in a partial decompression of the rowid column. The problem was then that the partially decompressed vector was used in another part where the full vector was required. I have fixed this in  8a7cf974f7372a66e837b9cfa5d5c3929e1f625f.
