### ISSUE TITLE
Incorrect result for MIN() on expression involving rowid

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#609]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT, c1 INT);
INSERT INTO t0(c0) VALUES (0), (0), (0), (0), (0), (0), (0), (0), (0), (0), (0), (0), (0), (0), (0), (0),  (0), (0), (0), (0), (0), (0), (NULL), (NULL);
CREATE INDEX b ON t0(c1);
UPDATE t0 SET c1 = NULL;
SELECT MIN(100000000000000000<<t0.rowid) FROM t0; -- unexpected: {0}
```
Unexpectedly, the `SELECT` fetches 0, although there are values smaller than zero contained in the table. Interestingly, adding a `WHERE` clause results in a smaller minimum value:
```sql
SELECT MIN(100000000000000000<<t0.rowid) FROM t0 WHERE NOT c0; -- -8802109549835190272
```
I found this based on commit a382ba05a7d6c0abb0c8f8f50b2bdf3a4e480704.

**Comment by Mytherin** [comment]
Should be fixed. The problem was that we used the minimum value of the domain (-2^63) to check whether or not a value had been set. This value was then written to the MIN, after which it was overwritten again by 0 because this value effectively "reset" the counter. Now we use a separate boolean to keep track of this.

**Comment by mrigger** [comment]
Based on your explanation, the following (manually-derived) test case would have been better applicable to demonstrate the underlying bug:
```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES (-1);
SELECT MIN(CAST(c0 AS BIGINT) << 63) FROM t0; -- expected: {-9223372036854775808}, actual: {NULL}
```
