### ISSUE TITLE
Failed ALTER COLUMN results in a "Transaction conflict" error that cannot be aborted 

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#618]
Consider the following statements:
```sql
CREATE TABLE t0(c0 DATE);
INSERT INTO t0 VALUES (DATE '2000-01-01');
ALTER TABLE t0 ALTER COLUMN c0 SET DATA TYPE INT;
INSERT INTO t0 VALUES (DEFAULT); -- TransactionContext: Transaction conflict: adding entries to a table that has been altered!
```
Unexpectedly, the `INSERT` results in `Error: TransactionContext: Transaction conflict: adding entries to a table that has been altered!`. A `ROLLBACK` or `COMMIT` does not help in resetting the state.

I found this based on commit 0e4b94f958b120fdaad45bda594933a2b84fced5.

**Comment by Mytherin** [comment]
Great find!

The problem here was that the ALTER TABLE works by creating a second 'new' version of the table in a version chain, like follows:

```
NEW <- OLD
```

When the new table is created, the old table is marked as 'stale' and cannot be appended to anymore. Normally, when the ALTER TABLE is rolled back, the old table is put back in the original position and is no longer considered stale.

The bug here was that the old table was marked as stale, but the new table was never added to the chain because the data type conversion failed while creating it. Thus there was no new table to roll back, and the old table was stuck in its stale state.
