### ISSUE TITLE
DROP column results in an assertion failure unique.index < base.columns.size().

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#625]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT, c INT UNIQUE);
ALTER TABLE t0 DROP c0; -- Assertion `unique.index < base.columns.size()' failed.
```
Unexpectedly, the `ALTER TABLE` results in an assertion failure:
```
/duckdb/src/planner/binder/statement/bind_create_table.cpp:60: void BindConstraints(duckdb::Binder&, duckdb::BoundCreateTableInfo&): Assertion `unique.index < base.columns.size()' failed.
```
I found this based on commit b6a065d6ebbab25ae8e023cf1105c5237f26de46.

**Comment by Mytherin** [comment]
Thanks! This failed because the index that points to the UNIQUE column was not updated on the alter, and remained on index #1 after dropping the column, when it should have been shifted by one. This should be fixed now.

Note that we don't support this ALTER TABLE statement yet, however. For now we don't support dropping columns when indexes exist on either (1) that column itself, or (2) any column AFTER that column. The reason for that is because we need to support multiple versions of indexes to properly support that, as after the DROP there will be two "versions" of the index, one that has the column at position #0 (new), and one that has the column at position #1 (old). Nothing too major, but I haven't gotten to it yet.

**Comment by mrigger** [comment]
Sounds good, so I guess it is better that I stop testing dropping columns for now, and not report errors, crashes, or assertion errors related to this feature, right?

**Comment by Mytherin** [comment]
No, please don't! :)

I was just saying this ALTER TABLE is supposed to return an error and explaining why. The correct behavior is to throw the error, which it does now. It is indeed still a bug if it throws any assertions or corrupts anything :)

**Comment by mrigger** [comment]
Ah, I see. Thanks for the clarification and sorry for my misunderstanding!
