### ISSUE TITLE
Microsecond resolution for timestamps

### ISSUE THREAD

**Issue by franksmithxyz** [cwida/duckdb#650]
Hello,

I'm interested in implementing higher resolution for timestamps, specifically microsecond.

For someone with a lot of C and C++ experience, how significant of an effort would this be to do it the right way, i.e. in a way that might be acceptable as a PR?

**Comment by Mytherin** [comment]
I think that would not be terribly complex - timestamps are not used in that many test cases and we do not have any backwards compatibility to maintain yet for storage. We would be happy to see a PR for this, but first we should do some bikeshedding ;)

For timestamps, currently we store these composed of a date and a time. I then propose we move to storing them as microseconds since the unix epoch as (signed) int64_t. For microseconds, we need to store `86400000000` microseconds per day, which means we can store the years 1970±292471.

If we were to move to nanoseconds, we could store the years 1970±292. This I think is too restrictive. So for 64-bits, microseconds seems reasonable.

The years 1970±292471 are slightly more restrictive than our current DATE type (which goes from -5867411 to 5867411), but I believe that those extra years are not very relevant and we can simply do a bounds check on inserting dates for the years that fit inside a timestamp. We can do that by changing YEAR_MAX and YEAR_MIN in `src/common/types/date.cpp`.

We then also need to take care that the `TIME` type should support microseconds as well, to prevent any inconsistencies. Since the microseconds for a single day require 37~ bits to store, we need to upgrade the `TIME` type. I suggest changing this to an int64_t as well for simplicity. This will waste some bytes; but those can later be recovered through compression again.

The parts that need to be changed to move to this new timestamp format are then:

* The timestamp code in `src/common/types/timestamp.cpp`
* The time code in `src/common/types/time.cpp`
* Any conversion code in the R/Python connectors (I can help with this if you need any help)

**Comment by Mytherin** [comment]
This is now implemented
