### ISSUE TITLE
DuckDB cannot read SQLite database files

### ISSUE THREAD

**Issue by mshmsh1234** [cwida/duckdb#655]
When I execute this line: 

conn = duckdb.connect('cdeschools.sqlite')

(using this data: http://2016.padjo.org/tutorials/sqlite-data-starterpacks/#toc-california-school-sat-performance-and-poverty-data)

I receive this error: RuntimeError: IO: Corrupt database file: computed checksum 8840056988481796550 does not match stored checksum 7358993341780611411 in block

I have no issue connecting to the DB using sqlite: 
con = sqlite3.connect("cdeschools.sqlite")

I received this corrupt database error in DuckDB after trying multiple different DBs. Why is this an issue with DuckDB and how can it be resolved?

**Comment by Mytherin** [comment]
I think there is some confusion: DuckDB is not compatible with the SQLite database format. You cannot open a SQLite database file in DuckDB. At least not currently; we might implement this in the future. In order to use DuckDB you need to convert the data inside the SQLite database to a DuckDB database. You could do this, for example, by opening the file with SQLite and writing the data to a CSV, then loading the CSV data into a DuckDB database.

I will leave this issue open because I think it reveals an important point: we need to give a descriptive error message here. In particular, we should prefix the database with a series of bytes indicating that it is a DuckDB database, and throw an error ("not a DuckDB database") when those bytes are not found.

**Comment by mshmsh1234** [comment]
Thank you! Yes, definitely confusion on my part. Thanks for the suggestion.

**Comment by mshmsh1234** [comment]
c.execute("COPY tweets FROM 'Tweets.csv';")

Is this the correct syntax to read from a CSV in duckdb python? This is throwing errors

**Comment by Mytherin** [comment]
That is the correct syntax, but perhaps you need to specify whether or not the file has a header or whether or not there are delimiters. See [here](https://www.duckdb.org/docs/current/sql/copy.html) for more information.

You can also use the automatic CSV dialect reader. Try this:
```sql
INSERT INTO tweets SELECT * FROM read_csv_auto('Tweets.csv');
```

If that still throws errors please include which errors it throws :)

**Comment by hannesmuehleisen** [comment]
We could detect the SQLite magic bytes and throw a dedicated error to make this more obvious.
