### ISSUE TITLE
ATTACH

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#665]
Hi!
Does DuckDB support any equivalent of the [sqlite ATTACH](https://www.sqlite.org/lang_attach.html) functionality?

**Comment by hannesmuehleisen** [comment]
This is not supported at the moment, sorry.

**Comment by ak2k** [comment]
No worries, thank you for the reply!

In terms of motivation (for context), ATTACH in sqlite provides some big benefits in my use case:
- query across independent datasets (files) at runtime with minimal overhead (given ATTACH is fast)
- version data easily using the file container to store data versioned together, then access the desired version of runtime by ATTACH-including the desired version

Depending on the implementation, perhaps there may be query performance benefits from parallel IO if the dbs being accessed are are stored on separate storage. Certainly there are major performance benefits from being able to load/prepare the independent datasets in parallel (as separate files).

To replicate this ability to runtime query across independently versioned tables, it would seem to be necessary to first load all the data combinations into a duckdb db container each time?

For someone new to the project, do you think ATTACH would be difficult to add?

**Comment by hannesmuehleisen** [comment]
I think this should be rather straightforward for read-only queries on the "attached" databases via a table-producing function. Changes to the attached databases, especially if transactions span multiple of them would be far more challenging. It depends on your use case whether this is acceptable to you.

**Comment by Alex-Monahan** [comment]
I have recently run into a data engineering use case for this feature. Maybe there is another way to approach the problem that you recommend that I could accomplish without it! I am using the Python API.

I'm downloading 500 million rows in chunks from Teradata in order to do recursive queries on the data that will benefit from DuckDB's vectorisation. 

Because my queries are recursive, eventually all of the data must be in the same table. I had hoped to insert into the same DuckDB from multiple processes, but DuckDB only uses a single writer. 

So, I can pull this data in parallel and store it in separate DuckDB's (or separate Parquet files, etc.). However, what is the fastest way to combine that data together into a single DuckDB?

**Comment by hannesmuehleisen** [comment]
If you have separate parquet files a `UNION ALL` between multiple `SELECT * FROM parquet_scan()` queries should work well enough.

**Comment by Alex-Monahan** [comment]
Ok, that sounds good! Will the new multi-thread feature allow multiple threads to work on those tasks at once?

**Comment by Mytherin** [comment]
Currently I believe UNION ALL is not yet parallelized, but it is rather easy to do so and will be added later on for sure. Another idea we had before was to add a `read_duckdb` function, similar to the `read_csv` and `read_parquet` functions, that allow you to read a table from a different database (e.g. `SELECT * FROM read_duckdb('test.db', 'integers')`. That might solve the problem for your use case as well.

For now I recommend using Parquet files over the DuckDB storage for anything persistent, however. The DuckDB storage is not stable yet and is changing in every release, which means upgrading the system to a newer version will break compatibility with any previous storage versions. We will stabilize the storage when version 1.0 is released, but it will likely take another year or so to get to that point.

**Comment by Alex-Monahan** [comment]
Thank you both for the great advice! I am now using Parquet to download my data in parallel, and then loading it into a DuckDB from those parquet files sequentially. I'm doing those read into duckdb operations one file at a time since I already have individual parquet files, but further down the road, having a parallel union all would let me speed things up by doing several of those at a time! I will say that it is pretty speedy already.

In the 1.0 timeframe, a read_duckdb function would definitely meet my use case (but I'll use Parquet for now based on your suggestion). I think that would also solve the IO parallelization opportunity that was mentioned earlier in this thread. Sounds like most of the benefits of attach without most of the complexity.

**Comment by ak2k** [comment]
Hi Guys!
As a quick follow-up, for read-only queries on "attached" tables emulated via the table-emitting function approach, would it be accurate to say that queries could benefit from filter pushdown but would not benefit from any indexes?
