### ISSUE TITLE
Range filters on empty/scarcely populated value ranges

### ISSUE THREAD

**Issue by tdoehmen** [cwida/duckdb#694]
I encountered an issue with filter conditions on a ~30M row dataset. The problem arises when using a `WHERE x BETWEEN value1 AND value2` or `WHERE x > value1 AND x < value2` condition on value ranges which are not present (or only very scarcely) in the dataset. While scanning for values within this range, a Stack overflow error occurs - on my system at about 1GB of memory consumption by the process. Some preliminary debugging lead me to the Adaptive Filters, but I get a bit lost beyond that. 

The following code should help to reproduce the issue. 

First generate some data:
```
import pandas as pd
import numpy as np
np.random.seed(1)
df = pd.DataFrame(np.random.uniform(-10,10,size=(30000000, 4)), columns=list('xyzn'))
df.to_csv("test.csv",index=False)

import duckdb
con = duckdb.connect(database='testdb', read_only=False)
con.execute("CREATE TABLE test AS SELECT * FROM read_csv_auto('test.csv');")
con.close()
```

Then, either execute in the python client:
```
con = duckdb.connect(database='testdb', read_only=False)
con.execute("SELECT * FROM test WHERE x > -11.0 and x < -10.0 LIMIT 10;")

```
Or in the duckdb cli:
```
.open testdb
 SELECT * FROM test WHERE x > -11.0 and x < -10.0 LIMIT 10;

```

**Comment by Mytherin** [comment]
Thanks for the bug report! I can confirm this breaks for me as well. Seems to be related to dictionary vectors; likely a circular reference that results in the stack overflow. Nice find :) I will take a better look after the weekend.

**Comment by Mytherin** [comment]
Should be fixed in the `sqlsmith-fixes` branch. The problem was that calls to ScanBaseTable would apply a dictionary vector, but not return anything as no matches were found. Then ScanBaseTable would be called repeatedly which kept on adding nested DictionaryVectors. This lead to a very deeply nested vector structure, which caused a stack overflow upon destruction. Calling Reset between every iteration should fix the unintended nesting behavior.

Could you verify that this works in the sqlsmith-fixes branch?

**Comment by tdoehmen** [comment]
I can confirm that the latest version of the `sqlsmith-fixes` branch solves the issue on my system using the original dataset/query. Thanks a lot for the super fast fix.
