### ISSUE TITLE
Global Regex Replace (and other extended options for regexp_replace/regexp_matches)

### ISSUE THREAD

**Issue by Alex-Monahan** [cwida/duckdb#753]
Hi all,

We are having trouble getting the Regex Replace function to do a global replacement. Is there a way to pass in Regex options or parse those off of the Regex expression? Here is the behavior we are seeing:

/* Test DuckDB regexp_replace to replace all matches */

select

  orig_text,

  regex,

  replace_text,

  expected_result,

  regexp_replace(orig_text,regex,replace_text) as result,

  regexp_replace(orig_text,regex,replace_text) = expected_result as test_passed

from (select 'test tweet' as orig_text, 't\w*t' as regex, 'woot' as replace_text, 'woot woot' as expected_result) test

![Screenshot_20200712-113939](https://user-images.githubusercontent.com/52226177/87254043-7f38e500-c434-11ea-91d8-e3cac886bf3f.png)

**Comment by Mytherin** [comment]
Thanks for opening this issue!

Indeed it looks like the regexp_replace only replaces the first occurrence that it finds currently. This seems to at least be consistent with Postgres, but Postgres has additional flags that can be specified as an optional fourth parameter.

In Postgres the syntax for this would be

```sql
select regexp_replace('test tweet', 't\w*t', 'woot', 'g');
```

Other supported flags can be found [here](https://www.postgresql.org/docs/9.4/functions-matching.html#POSIX-EMBEDDED-OPTIONS-TABLE).

I argue we should support the following options:

| Flag | Behavior |
|----:|----------|
|g | replace all occurrences of match instead of only first one |
| i | case-insensitive matching|
|m | historical synonym for n|
|n | newline-sensitive matching|
|s | non-newline-sensitive matching (default)|

regexp_matches should also support these flags.

I can work on adding this later this week, if nobody else is directly interested.

**Comment by Mytherin** [comment]
Should be implemented now :)
