### ISSUE TITLE
Re-enable CREATE INDEX for SQLite logic tests

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#776]
In the long long ago we disabled `CREATE INDEX` statements in the SQLite logic tests because there was no index support in DuckDB at all. Now there is and there seems to be at least the following two issues:

- third_party/sqllogictest/test/evidence/slt_lang_droptable.test:40: statement error
this one seems to be related to dropping an index after dropping the table which should lead to an error but doesn't
- third_party/sqllogictest/test/evidence/slt_lang_update.test:88: statement error
this looks like a multi-column update on a partially indexed table

Perhaps @pdet can have a look?

**Comment by pdet** [comment]
Hum, I don't think we support partial indexes.

Will have a look at them this week.

**Comment by hannesmuehleisen** [comment]
Thanks!

**Comment by Mytherin** [comment]
Had a look at these and they don't seem to be directly related to the index itself.

*third_party/sqllogictest/test/evidence/slt_lang_droptable.test*
```sql
DROP INDEX t1i1;
```

This is related to dependency management around the index; indeed the index should be dropped when the table is dropped. 

*third_party/sqllogictest/test/evidence/slt_lang_update.test:88*
```sql
UPDATE t1 SET x=3, x=4, x=5
```

We fail here because we disallow the same column from occurring twice in an UPDATE statement; apparently SQLite allows this. We could change this to match the behavior of SQLite.

If these are the only issues remaining I think we can fix those quite easily and enable the indexes in the sqllogictests.

**Comment by Mytherin** [comment]
This has been done
