### ISSUE TITLE
Error when insert timestamps containing T delimiter

### ISSUE THREAD

**Issue by bwgoudey** [cwida/duckdb#822]
I'm trying to import a table that contains a series of timestamps that contain a 'T' delimiter (e.g. 2009-11-11T15:21:19) as per the ISO 8601 standard but I'm getting an error from duckdb. As a short example (using the python interface):
```
con = duckdb.connect(database=':memory:', read_only=False)
con.execute(f"CREATE TABLE tmp(testdate TIMESTAMP);")
con.execute(f"INSERT INTO tmp VALUES ('2009-11-11 15:21:19'), ('2009-11-11T15:21:19');")
```
results in the following error
```
RuntimeError: Conversion: time field value out of range: "T15:21:19", expected format is ([YYY-MM-DD ]HH:MM:SS[.MS])
```
It seemed odd to me that only the second part of the data format was returned as an error. I did some digging and FromString(string str) in 'src/common/types/timestamp.cpp' seems to indicate that the 'T' should be accepted, at least based on the comments and my quick read of the code. 
```
// string format is YYYY-MM-DDThh:mm:ssZ
// T may be a space
```

Am I doing something incorrect in my insertion in the above example or is there some sort of quotes/escaping I can use to make this work?

**Comment by Mytherin** [comment]
Thanks for the bug report! This seems to be an issue in the timestamp parsing, the comment seems to not indicate exactly what is actually going on in the code. The code parses the DATE and TIME separately. The space works because the TIME parsing skips any leading or trailing spaces, but the "T" is not accepted by the parser here. I will fix it next week.

**Comment by Mytherin** [comment]
Should be fixed in the "strftime" branch now, I will close this issue when I merge it.
