### ISSUE TITLE
error message when trying to open database

### ISSUE THREAD

**Issue by luxint** [cwida/duckdb#847]
I get the error message :  "Exception in WAL playback: Serialization: not enough data in file to deserialize result when trying to open an existing  database" . Happens with the CLI, as well as through the C API,  with a build from august 14 and a build i made today.  Build i made from august 7 or earlier are working fine with this database.
[duckdbtest.tar.gz](https://github.com/cwida/duckdb/files/5090429/duckdbtest.tar.gz)

**Comment by Mytherin** [comment]
Currently the DuckDB storage format is in pre-release mode and not stable. That means the storage format can change in non-backwards compatible ways between essentially every commit. We currently do not want to stabilize the storage format or offer upgrade paths because that would make it significantly more difficult to change the storage. We should have more disclaimers for that, apologies!

We plan to stabilize the storage format when the 1.0 release comes around, but until that point we recommend you don't store important data inside DuckDB storage files without a backup elsewhere. Any update to a newer version might break compatibility with your older DuckDB files. An alternative option would be to use Parquet files, as DuckDB can both read and write those relatively efficiently.

Perhaps we could add `EXPORT DATABASE` and `IMPORT DATABASE` commands. The `EXPORT DATABASE` would dump the database to a self-descriptive stable format (e.g. a bunch of Parquet files with a JSON-like document that describes meta-information), and the `IMPORT DATABASE` can then read those again. Then you could manually upgrade the database file that way without too much effort.

**Comment by luxint** [comment]
Ah ok, I didn't know the storage format was not yet stable! Would be helpful to have a database backup option (maybe also zipped?), not only for now but also in the future when the storage format is stable . When do you expect the 1.0 release with the stable format?

**Comment by Mytherin** [comment]
Would the `EXPORT DATABASE` as described suit your needs? Perhaps we could expand it with a toggle of which format to use (PARQUET/CSV), with a potential compression on top of it (e.g. the directory could be zipped together).

The storage format will take some time; we are currently planning to do a major rework of the storage to allow for super flexible data compression (based on [white-box compression](http://cidrdb.org/cidr2020/papers/p4-ghita-cidr20.pdf), but expanded). Realistically it will take at least half a year for us to get that implemented.

**Comment by luxint** [comment]
Export (and import of course ;-)) would work fine for me, I don't think a toggle is needed, I would pick the format which works best/ is the fastest.

**Comment by Mytherin** [comment]
I have added support for the EXPORT/IMPORT database commands, see [here](https://duckdb.org/docs/sql/statements/export) for the documentation. We now also throw a better error message when loading a database file from an older DuckDB version, see [this PR](https://github.com/cwida/duckdb/pull/858) for some more information.

Closing this issue for now. Feel free to re-open if you have other problems relating to the storage.
