### ISSUE TITLE
0.2.1 memory_limit does not apply to WAL flush

### ISSUE THREAD

**Issue by wizzard0** [cwida/duckdb#926]
STR:
```
.open 1.db
pragma memory_limit='1GB';
create table stars1 as select * from read_csv_auto('star2002-full.csv');
create table stars2 as select * from read_csv_auto('star2002-full.csv');
.open 1.db
```
peak memory consumption is just over 5G during second .open
dataset from https://sdm.lbl.gov/fastbit/data/samples.html

likely worth to investigate before #49 too

**Comment by Mytherin** [comment]
The problem here is that the pragma only applies to the first database, calling `.open` restarts the database, and thus removes the pragma. In principle the memory limit should be respected during the checkpoint. A fix here could be to "remember" options in the shell between calls to .open, but a more long-term fix is indeed to enable checkpointing during run-time and incremental checkpointing.

**Comment by hannesmuehleisen** [comment]
And I'd like to keep shell.c unmodified so it can be easily replaced ^^ #931

**Comment by wizzard0** [comment]
> The problem here is that the pragma only applies to the first database, calling `.open` restarts the database

well sure, but there's no way to insert the pragma before checkpointing :) i'm fine with hoops and workarounds, but when there's no way to limit RAM at all it's a problem

**Comment by Mytherin** [comment]
Indeed you are correct, in the `localstoragerework2` branch I have set the default memory limit to 80% of system memory. That should solve this problem in most use cases. To really solve it we need to allow other clients (besides the C++ one) to start the database with non-default settings.

**Comment by arjenpdevries** [comment]
Mark, is there a brief instruction on how to achieve this (setting a lower memory limit)? I would like to let some students look into IR collection ranking with DuckDB, but if they already run in trouble loading the tables, it will be hell to supervise :-)

**Comment by Mytherin** [comment]
This problem should only occur when re-loading a database after it has been saved on disk, and it should only be a problem if the data is bigger than the available memory. Working only in an in-memory database, or working with data smaller than 1GB~ shouldn't be a problem. Otherwise you will need to wait for my PR, which should hopefully be around this week.

**Comment by Mytherin** [comment]
Incremental checkpointing has now been implemented, which should remedy this issue as a full database rewrite is no longer necessary.

**Comment by wizzard0** [comment]
ahem... can't confirm. it's at 3G which is better than 5G at the exact same repro ;)

**Comment by Mytherin** [comment]
How are you measuring memory usage? Simply looking at `htop` or similar can be misleading, because the OS will keep around cached buffers even if they are not currently in-use by the system, which is outside of our control. What that means is that the system will work fine with 1GB of RAM, but since you have the extra memory lying around the OS will keep recently-accessed pages in RAM in case they are used again.

During the second .open nothing should actually be happening now besides reading some meta-data, so the effective memory usage of the system should be very low (maybe a few MB, regardless of how much data is in the database).

**Comment by wizzard0** [comment]
No, during inserts the memory usage stays low (under 1 GB).
Then the WAL grows to about 2.8 G, and the second .open causes WAL flush, with peak memory at 3.1G.
Afterwards the memory used drops to under 300MB

**Comment by Mytherin** [comment]
Ah yes, you are correct. If the database does not exit properly (or checkpointing on exit is disabled) the system will do a WAL replay on startup which will only respect the limit set during database creation. For the shell I think we can fix this by keeping the "DBConfig" of the system around and passing that to the new database that is created when using `.open`, that way pragmas that affect the configuration are persisted across `.open` calls.

**Comment by wizzard0** [comment]
wow wow added reminder to verify with 0.2.5 now

**Comment by wizzard0** [comment]
memory_limit still does not survive reopen ;), but a) everything became A LOT faster! 2) reopen consumes minimal memory so limit can be set after second .open

overall impressed w\0.2.5 and duckdb in general, great work guys!
