### ISSUE TITLE
Confusing error message from CSV AUTODETECT

### ISSUE THREAD

**Issue by fire-eggs** [cwida/duckdb#972]
Bug: got a different (and wrong!) error messages from CSV import when using AUTO_DETECT.

[Using the python interface, where "c" below is a cursor on the db connection.]
My table:
```
    c.execute('''CREATE TABLE imageTags
                 (image_id INT,
                  tag_id INT,
                  PRIMARY KEY(image_id,tag_id))''')
```
NOTE: three columns.

The CSV to import (sample subset):
```
tag_id|name|category|count
470575|1girl|0|2612433
16751|bangs|0|527398
11826|barefoot|0|165731
537684|blunt_bangs|0|76594
```
NOTE: four columns.

Attempt 1:
```
    c.execute("COPY tags FROM 'tags.csv' ( AUTO_DETECT TRUE )")
```
Error message: RuntimeError: Parser: Error on line 2: expected 3 values but got 1

Attempt 2:
```
    c.execute("COPY tags FROM 'tags.csv' ( DELIMITER '|', HEADER )")
```
Error message: RuntimeError: Parser: Error on line 2: expected 3 values but got 4

**Comment by tdoehmen** [comment]
Hi, I tried to reproduce the issue based on your provided examples

1. I changed the table name from `imageTags` to `tags` in the `CREATE TABLE` statement. I hope that this is was correct.

2. The resulting table `tags` has 2 columns and a primary key constraint on my system, not 3 columns.

3. I assume that what you intended to do was to import the `tags.csv` file into the just created `tags` table. Correct? Currently, we do not support an automatic filtering of columns based on the target schema, but it is a planned feature for future releases (see https://github.com/cwida/duckdb/issues/782)

4. Now to the error messages you got. I could actually not reproduce the same messages. Instead, I received the following output, which I can also explain:
 `COPY tags FROM 'tags.csv' ( AUTO_DETECT TRUE )` 
-->
`Parser: Error on line 2: expected 2 values but got 1`
The parser expects 2 values (per column) because it looks at the `tags` schema at hand. It only got one column because it dismissed the `|` separator as a possible option because it would have resulted in 4 columns which would have been too many. Therefore it fell back to default parameters (comma separation) which resulted in 1 value (per column). 
 `COPY tags FROM 'tags.csv' ( DELIMITER '|', HEADER )` 
-->
`Parser: Error on line 2: expected 2 values but got 3`
Here, the parser expects 2 values again (based on the provided `tags` schema), but as it got to the 3rd value in the column it stopped with an error message.

I understand that the error messages are not very expressive and should be improved. Thanks for the report.

**Comment by fire-eggs** [comment]
D'oh! Copy-pastad the wrong table:
```
    c.execute('''CREATE TABLE tags
                 (tag_id INT,
                  name TEXT,
                  category INT)''')
```
My apologies for the mixup. You were able to repro the essence of the issue.

> It only got one column because it dismissed the | separator as a possible option because it would have resulted in 4 columns which would have been too many.

Reasonable enough! That is actually a clever attempt to be smart.

**Comment by Mytherin** [comment]
Perhaps an idea would be to add the detected settings to the error message in case auto detect is enabled. For example:

```sql
RuntimeError: Parser: Error on line 2: expected 3 values but got 1 (DELIMITER ',', HEADER 1)
```

**Comment by tdoehmen** [comment]
Right! That would be cool. Let me push a change.

**Comment by Mytherin** [comment]
I think that this has been resolved now with the latest error message updates. Feel free to re-open if you have more issues related to this.
